### ISSUE TITLE
Network Interceptor

### ISSUE THREAD

**Issue by lhyjason** [smaugho/declex#101]
Is it possible to have interceptor on each request? And can it support [Stetho](http://facebook.github.io/stetho/) ?

**Comment by smaugho** [comment]
It is planned already a "controller" to be used when injecting Models, I'm referring to issue #43. Once the controller mechanism be implemented, then a Network Interceptor would be something important to add... I will read more about Stetho to see the possibility to add it... Please feel free to propose mechanism to use this feature.

**Comment by lhyjason** [comment]
Thanks! Really looking forward to DecleX to become more powerful and popular in Android development!!!

**Comment by smaugho** [comment]
Well actually, the framework right now supports already to do this.. Let's say that you have a Model:

```java
@ServerModel(...);
public class SomeModel {

    @ServerModel
    static OkHttpClient okHttpClient = new OkHttpClient.Builder()
            .addNetworkInterceptor(new StethoInterceptor())
            .build();
}
```

When `@ServerModel` creates the requests, it will use as client any static field annotated with "@ServerModel" of type "OkHttpClient".

Give it a try ;-)

```

**Comment by lhyjason** [comment]
Cool !!! It works well !!! Thanks!!!
