### ISSUE TITLE
Handle SocketTimeoutException

### ISSUE THREAD

**Issue by lhyjason** [smaugho/declex#104]
When we get SocketTimeoutException, the generated code doesn't handle it. Is is possible to handle this exception in the framework? Or we can manually handle it ?

**Comment by smaugho** [comment]
Hi. You can handle the SocketTimeout directly using the OkHttpClient.

Let's say that you have a Model:

```java
@ServerModel(...);
public class SomeModel {

    @ServerModel
    static OkHttpClient okHttpClient = new OkHttpClient.Builder()
                                                          .connectTimeout(1260, TimeUnit.SECONDS)
                                                          .readTimeout(1230, TimeUnit.SECONDS)
                                                          .build();
}
```

When `@ServerModel` creates the requests, it will use as client any static field annotated with "@ServerModel" of type "OkHttpClient".

If you want to apply the same okHttpClient for whole your app, you can declare it Static and use in every model, ex:

```java
@ServerModel(...);
public class SomeModel {

    @ServerModel
    static OkHttpClient okHttpClient = ServerUtils.OK_HTTP_CLIENT;
}
```

**Comment by smaugho** [comment]
Or in case you want to handle a specific thrown error, you can do it with actions when injecting the Model:

```java
@Model(lazy = true)
SomeModel myModel;

@AfterInject
void initModel() {
    $LoadModel(myModel);
    if ($LoadModel.Failed) {
        Throwable $e = null;
        $e.printStackTrace();
    }
}
```

>Note: if you use the internal build "1.2.1.6" for DecleX, you can use also:

@AfterInject
void initModel() {
    $LoadModel(myModel);
    if ($LoadModel.Failed) {
        $LoadModel.Failed().e.printStackTrace();
    }
}
```

>Please note that this Build can be unstable. 

If you want to handle this by the model, you can do it also like this inside your model which uses @ServerModel:

```java
    @ServerModel
    static void handleConnection(Exception e) {
        if (e != null) ....
    }
```
In this method you can take also as parameters the Response or Request object.

**Comment by smaugho** [comment]
Important!.. in general the errors are handled better when the Actions are used to Load/Put the model... so if in your code you run as above:

```java
    $LoadModel(myModel);  //or $PutModel(myModel);.. 
    if ($LoadModel.Failed) {
        //Here the errors are being handled
    }
```

**Comment by smaugho** [comment]
I do agree that when injecting the model, like:

```java

@Model(async = true)
MyServerModel myModel;

```

The exceptions should be automatically handled (so, not thrown to avoid crashes).. I will set this as something to be fixed.

**Comment by smaugho** [comment]
To fix this defect I also suggest that the @Model annotations run a validation on the Model Types, so @ServerModel could detect for instance the NetworkOnMainThread exception, and hint the programmer about using the `handleExceptions` flag.
