### ISSUE TITLE
@FragmentByTag is useless in methods of actions

### ISSUE THREAD

**Issue by yasmanmesa** [smaugho/declex#105]
When a class is defined to create an action and the annotation is used to instantiate a fragment by its tag, it creates a method in the generated subclass called "onViewChanged" where this fragment is searched:
```java
    @Override
    public void init(final String parameter) {
        SomeObjectActionHolder_.super.init(parameter);
    }

    @Override
    public void build() {
        IntentIntegratorActionHolder_.super.build();
    }

    @Override
    public void execute() {
        IntentIntegratorActionHolder_.super.execute();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        this.someFragment = ((Fragment) findSupportFragmentByTag("someTag"));
    }
```
The actions have 3 fundamental methods: init, buil and execute, which are executed before the "onViewChanged" method so the fragment will always be used in these methods and will throw a NullPointerException.

**Comment by smaugho** [comment]
Hi, could you please provide some part of your code, I don't get the point, it is supposed that you use the Action from a different fragment to the one where you use @FragmentByTag to gather that fragment...

**Comment by yasmanmesa** [comment]
I'm working on an action to do any kind of "Intent" (scanner, gallery, camera, etc.) by simply calling an action with parameters: 
```java
$IntentIntegrator("tag", "scanner");
```
During the development of this action was in this state:
```java
@ActionFor(value = "IntentIntegrator")
public class IntentIntegratorActionHolder  {

    String intentType;

    @RootContext
    Context context;

    @FragmentByTag
    Fragment TopTabs;

    void init(String type) {
        this.intentType = type;
    }

    void build() {
        Activity activity = (Activity) context;
        IntentIntegrator integrator = new IntentIntegrator(activity) {
            @Override
            protected void startActivityForResult(Intent intent, int code) {
                TopTabs.startActivityForResult(intent, Config.SCANNER_REQUEST);
            }
        };
        integrator.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);
        integrator.setPrompt(activity.getResources().getString(R.string.scan_barcode));
        integrator.setCameraId(0);
        integrator.setBeepEnabled(false);
        integrator.setBarcodeImageEnabled(true);
        integrator.setOrientationLocked(false);
        integrator.initiateScan();
    }

    void execute() {
    }
}
```
When you use the fragment to call the intent, the fragment is null because the fragment has not yet been searched for by the tag, so it returns an error.

**Comment by yasmanmesa** [comment]
So use it in TopTabsFragment:
```java
    @Click
    void touch(){
        $IntentIntegrator("scanner");
    }
```

**Comment by yasmanmesa** [comment]
For more understanding I will explain more so that they understand me all:
I want to make an action to use the IntentIntegrator. Currently I do this to modify the scanner properties:
```java
    @Click
    void search(){
        IntentIntegrator integrator = new IntentIntegrator(getActivity()) {
            @Override
            protected void startActivityForResult(Intent intent, int code) {
                TopTabsFragment.this.startActivityForResult(intent, Config.SCANNER_REQUEST);
            }
        };
        integrator.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);
        integrator.setPrompt(getString(R.string.scan_barcode));
        integrator.setCameraId(0);
        integrator.setBeepEnabled(false);
        integrator.setBarcodeImageEnabled(true);
        integrator.setOrientationLocked(false);
        integrator.initiateScan();
    }
```
But I would like to come up with something like this:
```java
    @Click
    void search(){
        $IntentIntegrator("scanner");
    }
```
In the process of development of the action "$IntentIntegrator" reaches this point:
```java
@ActionFor(value = "IntentIntegrator")
public class IntentIntegratorActionHolder  {

    String intentType;

    @RootContext
    Context context;

    @FragmentByTag
    Fragment TopTabs;

    void init(String type) {
        this.intentType = type;
    }

    void build() {
        Activity activity = (Activity) context;
        IntentIntegrator integrator = new IntentIntegrator(activity) {
            @Override
            protected void startActivityForResult(Intent intent, int code) {
                TopTabs.startActivityForResult(intent, Config.SCANNER_REQUEST);
            }
        };
        integrator.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);
        integrator.setPrompt(activity.getResources().getString(R.string.scan_barcode));
        integrator.setCameraId(0);
        integrator.setBeepEnabled(false);
        integrator.setBarcodeImageEnabled(true);
        integrator.setOrientationLocked(false);
        integrator.initiateScan();
    }

    void execute() {
    }
}
```
I can not use the @FragmentByTag because when it was run:
```java
TopTabs.startActivityForResult(intent, Config.SCANNER_REQUEST);
```
... it returns a NullPointerException because the TopTabs fragment is still null, it has not yet been searched for by the tag.

**Comment by smaugho** [comment]
Thank you very much for submitting your code.. I've tested this issue and it can be reproduced. Basically the `onViewChanged` of the @ActionFor (Action Handler) would be never called because the onViewChangedListener that is registered when creating the underlying @EBean will be called only after a view update. 

Since the @ActionFor (@EBean dependent) is not creating during the creation of the fragment, the onViewChanged method should be triggered manually.

The issue is solved if before the "init" face of the Action being created, it is called its `onViewChanged` listener, passing the Enhanced Activity or Fragment as parameter. 

Now, see that this should be done only if `onViewChanged` was not called for the declaring Activity or Fragment before. 

Also for the @ActionFor be registered for the changes later in the Views, the `getInstance` method should be called similar like when init is called.. so, in general:

```java
   OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
   IntentIntegratorActionHolder  holder = IntentIntegratorActionHolder_.getInstance(this);
   OnViewChangedNotifier.replaceNotifier(previousNotifier);
   holder.onViewChanged(this);
```
