### ISSUE TITLE
Delete the view of the parent element when a $AlertDialog is hidden

### ISSUE THREAD

**Issue by yasmanmesa** [smaugho/declex#123]
It would be very useful that when a dialogue is hidden, the view that is associated with the parent is removed, so that it does not have to be done. It is a step that could be incorporated in this action. Currently something like this is done to fix this situation:
```
ViewGroup parent = (ViewGroup)view.getParent();
parent.removeView(view);
```

**Comment by smaugho** [comment]
This is useful when is passed a View parameter to the dialog (a view inflated outside).
