### ISSUE TITLE
use of RxAppCompatActivity as base activy crash the compilation

### ISSUE THREAD

**Issue by ftoyon** [smaugho/declex#173]
Hi,

I want to use rxlifecycle components version 1.0 but when I use the RxAppCompatActivity for activity class base the build crash with this stack :

15:29:51.837 [ERROR] [system.err] java.lang.NullPointerException
15:29:51.837 [ERROR] [system.err] 	at com.dspot.declex.override.holder.ActivityActionHolder.findExtraFields(ActivityActionHolder.java:145)
15:29:51.837 [ERROR] [system.err] 	at com.dspot.declex.override.holder.ActivityActionHolder.findExtraFields(ActivityActionHolder.java:158)
15:29:51.837 [ERROR] [system.err] 	at com.dspot.declex.override.holder.ActivityActionHolder.findExtraFields(ActivityActionHolder.java:158)
15:29:51.837 [ERROR] [system.err] 	at com.dspot.declex.override.holder.ActivityActionHolder.addActivityExtraInformation(ActivityActionHolder.java:115)
15:29:51.837 [ERROR] [system.err] 	at com.dspot.declex.override.holder.ActivityActionHolder.createInformationForActionHolder(ActivityActionHolder.java:110)
15:29:51.837 [ERROR] [system.err] 	at com.dspot.declex.override.handler.EActivityHandler.validate(EActivityHandler.java:38)
15:29:51.837 [ERROR] [system.err] 	at org.androidannotations.handler.BaseAnnotationHandler.validate(BaseAnnotationHandler.java:103)
15:29:51.837 [ERROR] [system.err] 	at org.androidannotations.internal.process.ModelValidator.validate(ModelValidator.java:71)
15:29:51.837 [ERROR] [system.err] 	at org.androidannotations.internal.AndroidAnnotationProcessor.validateAnnotations(AndroidAnnotationProcessor.java:332)
15:29:51.837 [ERROR] [system.err] 	at com.dspot.declex.DeclexProcessor.validateAnnotations(DeclexProcessor.java:323)
15:29:51.837 [ERROR] [system.err] 	at org.androidannotations.internal.AndroidAnnotationProcessor.processThrowing(AndroidAnnotationProcessor.java:206)
15:29:51.837 [ERROR] [system.err] 	at org.androidannotations.internal.AndroidAnnotationProcessor.process(AndroidAnnotationProcessor.java:154)
15:29:51.837 [ERROR] [system.err] 	at com.dspot.declex.DeclexProcessor.process(DeclexProcessor.java:127)
15:29:51.837 [ERROR] [system.err] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
15:29:51.837 [ERROR] [system.err] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
15:29:51.837 [ERROR] [system.err] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
15:29:51.837 [ERROR] [system.err] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
15:29:51.837 [ERROR] [system.err] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
15:29:51.837 [ERROR] [system.err] 	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
15:29:51.837 [ERROR] [system.err] 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
15:29:51.837 [ERROR] [system.err] 	at com.sun.tools.javac.main.Main.compile(Main.java:523)
15:29:51.837 [ERROR] [system.err] 	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
15:29:51.837 [ERROR] [system.err] 	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
15:29:51.837 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)
15:29:51.837 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
15:29:51.837 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
15:29:51.837 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
15:29:51.837 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
15:29:51.837 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
15:29:51.837 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
15:29:51.837 [ERROR] [system.err] 	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:206)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:187)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:130)
15:29:51.838 [ERROR] [system.err] 	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
15:29:51.838 [ERROR] [system.err] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:29:51.838 [ERROR] [system.err] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:29:51.838 [ERROR] [system.err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:29:51.838 [ERROR] [system.err] 	at java.lang.reflect.Method.invoke(Method.java:498)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
15:29:51.838 [ERROR] [system.err] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:43)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:40)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:75)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.util.Swapper.swap(Swapper.java:38)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
15:29:51.839 [ERROR] [system.err] 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
15:29:51.839 [ERROR] [system.err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
15:29:51.839 [ERROR] [system.err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
15:29:51.839 [ERROR] [system.err] 	at java.lang.Thread.run(Thread.java:745)

**Comment by smaugho** [comment]
Hi @ftoyon, could you please share an snippet of your code? Is the crash as soon as you place the RxAppCompatActivity?

**Comment by ftoyon** [comment]
I just modify our template all for RxLifeCycle using and change the base class of MainActivity by RxAppCompatActivity.

[declex-example-ready-master.zip](https://github.com/smaugho/declex/files/1114376/declex-example-ready-master.zip)

**Comment by smaugho** [comment]
@ftoyon the problem seems to be completely fix in our internal build. I sent you attached the project with some small testings I was doing with it, no problem detected so far. Please note, the version of DecleX used is the current being developed, and it is in alpha development yet, so there's many features which are not documented, also when version 2.0 be published it will have other improvements. But feel free to use the last build we use in our internal projects, they are available in jCenter as well. 

[declex-example-ready-master.zip](https://github.com/smaugho/declex/files/1115050/declex-example-ready-master.zip)

**Comment by smaugho** [comment]
@ftoyon I will close the issue, please feel free to reopen if you see any other issue in the last version (sent with the project, version 2.0.a.5) related to **RxAppCompatActivity**
