### ISSUE TITLE
About documentacion

### ISSUE THREAD

**Issue by jxarenas19** [smaugho/declex#232]
Good morning, you have some intention to update the documentation with the new features included?

**Comment by smaugho** [comment]
Hi, definitely we'll be updating the documentation!!.. But also, note that the version 2.0 is not published yet, and it is under development, I think you are talking about the features on this version, we'll be on the next months working mainly on this version, to make it more stable, also to finish some extra features we think are important for this version, and which are complex. After (or during) publishing the version 2.0, I think to write some articles about the new features and work more actively in the documentation. 

Please, feel free to cooperate as well with the current documentation, or updating it to add the new features, I'll update it referencing the developing version to avoid versioning issues. 

Thanks!!!

**Comment by jxarenas19** [comment]
Good news!!
