### ISSUE TITLE
LocalDB Model add new column

### ISSUE THREAD

**Issue by email4shahbaz** [smaugho/declex#247]
I have a Model class User, I added a new column "age", when I run the app on a devices already have my app installed, it crashed with following error: "no such column 'age' exists".

I uninstalled and reinstalled the app on device and it worked (probably uninstalling the app removed db and created table 'user' with new filed 'age' added.

How can I add a new column/fields to existing local db table without such crash?

**Comment by smaugho** [comment]
@email4shahbaz , LocalDB Model is using ActiveAndroid, so you should use the migration mechanism of this lib:

https://github.com/pardom-zz/ActiveAndroid/wiki/Schema-migrations

**Comment by email4shahbaz** [comment]
Hi @smaugho , Thanks for the hint. I will try it.
